### ISSUE TITLE
Support for blood pressure measurement unit (millimeter of mercury - mmHg)

### ISSUE THREAD

**Issue by pedrosfdcarneiro** [joshwlewis/unitwise#23]
Hy :beer: 

I'm developing a health application and I'm using unitwise. I need to process a lot of different measurements and unitwise has been a great tool for the job.

However, when it comes to read the [blood pressure](https://en.wikipedia.org/wiki/Blood_pressure), unitwise seems to don't support **mmHg** ([millimeters of mercury](https://en.wikipedia.org/wiki/Millimeter_of_mercury)) unit.

Is this unit not supported yet? What can I do?

Thanks in advance.

**Comment by joshwlewis** [comment]
Hi,

It's a bit awkward, but the designation in [unitsofmeasure.org](http://unitsofmeasure.org/ucum-essence.xml) is `m[Hg]`. So `mm[Hg]` would be what you want to use. `millimeter of mercury column` also works.

```ruby
Unitwise(1, "mm[Hg]").convert_to("kPa")
=> #<Unitwise::Measurement value=0.133322 unit=kPa>

Unitwise(1, "millimeter of mercury column").convert_to("kPa")
# => #<Unitwise::Measurement value=0.133322 unit=kPa>
```

**Comment by pedrosfdcarneiro** [comment]
Well, thanks for the answer.

It is, indeed, a little bit awkard notation for this unit. I think it is uncommon to use square brackets in the notation.

But, at least, the unit exists :smiley:

There is any chance to create a kind of alias of ```mmHg``` to ```mm[Hg]```?

**Comment by joshwlewis** [comment]
Heya @pedrosfdcarneiro, I just released a new version of Unitwise that has custom unit registration. You could use it to create your own aliases, if you still wanted this. Check it out here https://github.com/joshwlewis/unitwise#adding-custom-units.
