### ISSUE TITLE
Canonical way to reference the unit?

### ISSUE THREAD

**Issue by andyw8** [joshwlewis/unitwise#25]
Let's say I have two measures which are equal, except than one uses the abbreviated form:

```
Unitwise(1, "kilogram")
Unitwise(1, "kg")
```

I want find a 'canonical' way to reference the unit so that I can persist it to a DB. I don't really mind if it's 'kg', or 'kilogram', as long as it's consistent.

Is there a way to do that through the public interface? I've been looking at the code and documentation but can't see an obvious way.

**Comment by andyw8** [comment]
Update: Here's how I'm doing it currently:

```ruby
term = Unitwise(quantity, unit).unit.terms.first
[term.prefix, term.atom].map(&:to_s).join
```

**Comment by joshwlewis** [comment]
Sorry for the terribly late reply, but the most canonical string representation would be `Unitwise(1, "inch/second").unit.to_s(:primary_code)`. `to_s` without arguments would use whatever string you used to initialize the unit (`"inch/second"` in this case). Specifying `:primary_code` forces Unitwise to use the unique identifier from UCUM. There's a caveat that while it's the canonical representation, some primary codes aren't human friendly: `Unitwise(1, "inch/second").unit.to_s(:primary_code)
=> "[in_i]/s"`.
