### ISSUE TITLE
Measurement attribute value setter should use BigDecimal

### ISSUE THREAD

**Issue by phlegx** [joshwlewis/unitwise#27]
Should the setter method of `measurement.rb` not use the same setter logic like in `scale.rb` using BigDecimal?

Here the line: https://github.com/joshwlewis/unitwise/blob/c76d203bf665676bb8b151ffc51d0894d88bbaa9/lib/unitwise/measurement.rb#L161

``` ruby
module Unitwise
  ...
  class Scale
    def value=(value)
      @value = BigDecimal(value.to_s)
    end
  end
end
```

**Comment by joshwlewis** [comment]
I didn't go that route on purpose, because I didn't want to lose track of the original `Numeric` type the user chose.

As I recall, coercing the numeric would yield weird strings like `Unitwise::Measurement.new(1, "meter").to_s => "0.1E1 meter"`.

Is this causing you an issue?

**Comment by phlegx** [comment]
I use a small hook that looks like this and it works fine:
```ruby
module Unitwise

  class Measurement < Scale
    private
    def value=(value)
      @value = (value.is_a?(BigDecimal) ? value : BigDecimal(value.to_s))
    end
  end

  class Scale
    def value=(value)
      @value = (value.is_a?(BigDecimal) ? value : BigDecimal(value.to_s))
    end
  end

end
```

**Comment by joshwlewis** [comment]
Now that #45 is merged, both `Meaurement` and `Scale` have the same value setter. Neither performs a conversion. I think this is the right approach as `BigDecimal(value.to_s)` potentially causes some accuracy loss.

If you think this is still an issue, can you provide some usage example that illustrates?
