### ISSUE TITLE
how to multi language units of unitwise

### ISSUE THREAD

**Issue by phil88530** [joshwlewis/unitwise#29]
Hi:

I'm a bit new to ruby gems, and wish to know if there's some quick way to multi language the unit, as when I run Unitwise(quantity, unit.measurement), I wish the printout can be in Chinese, any quick locale file setup I can try in order to achieve this?

**Comment by joshwlewis** [comment]
Hi @phil88530, I can't think of any *quick* setup that would rovide translations for the massive list of units in the UCUM spec. If you are only using a few units, perhaps you could handle your own translations?

For instance, in a Rails template:

```
<span><%= measurement.convert_to("meter").to_i %><% I18n.t("measurements.meter") %>
```
