### ISSUE TITLE
How to extend unitwise with custom units and conversions

### ISSUE THREAD

**Issue by Joseph-N** [joshwlewis/unitwise#30]
Hello,
I've been using unitwise for a while now and all is great. I was wondering is there a way to extend unitwise in my rails app and offer custom conversions? We have a bunch of custom converstions we'd like to provide users with, example is [brewing color converstions](https://www.brewtoad.com/tools/color-converter)

Any suggestions how to extend the gem and incorporate custom units and conversions will be highly appreciated.

Thanks!

**Comment by joshwlewis** [comment]
Roughly, you can implement your own atoms, something like this (response copied from #22):

```ruby

person_data = {:names=>"Person", :symbol=>"person", :primary_code=>"person", :scale=>{:value=>1.0, :unit_code=>"1"}, classification: "dimless"}

person = Unitwise::Atom.new(person_data)

Unitwise::Atom.all << person

Unitwise(10, "person")**2
=> #<Unitwise::Measurement value=100 unit=Pers2>

```

A few caveats here:

- Parsing results are memoized, so you'll need to load the Atom before you start using Unitwise elsewhere. Loading the atom in should probably happen in an initializer or something similar.
- There might be a set of properties that make more sense for you. Take a look [here](https://github.com/joshwlewis/unitwise/blob/master/data/derived_unit.yaml) to figure out atom initialization options.
- The fact that this works is somewhat unintentional, and certainly untested. It might behave strangely.

**Comment by joshwlewis** [comment]
Hi @Joseph-N, I just cut a new release that features custom unit registration. See https://github.com/joshwlewis/unitwise#adding-custom-units. Thanks for your feedback.
