### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by MDRecipes** [joshwlewis/unitwise#32]
Hello, I tried your method "http://joshwlewis.com/essays/r..." but it does not work, can you help me please, I block on it, I'm null on rails. my project : git@github.com:MDRecipes/mdrecipe.git

**Comment by joshwlewis** [comment]
Hi, can you provide an example of the code that isn't working? For instance, the code you wrote, what you expect it to do, and what it is actually doing?

**Comment by joshwlewis** [comment]
I'm going to close this for now. Feel free to comment if you can share specifics about the issue.
