### ISSUE TITLE
'm' to 'ft' conversion fails but 'm' to 'foot' works

### ISSUE THREAD

**Issue by sandeepnagra** [joshwlewis/unitwise#33]
Unitwise(1, 'm').convert_to('ft') fails with error - Unitwise::ConversionError: Can't convert 1 m to ft.

but,

Unitwise(1, 'meter').convert_to('foot') works: => #<Unitwise::Measurement value=3.280839895 unit=foot>

&

Unitwise(1, 'm').convert_to('foot') works too: => #<Unitwise::Measurement value=3.280839895 unit=foot>

**Comment by sandeepnagra** [comment]
Also, is it possible for you to add conversion logic for 'm/s' or any other speed unit to 'ft/min'?

**Comment by joshwlewis** [comment]
Hi @sandeepnagra -- this is a experience issue that I haven't figured out how to resolve. The root of the issue is that `ft` resolves to `femtotonne`, a proper SI measurement of mass. The official UCUM designation for foot is `[ft_i]`, which is ugly, but guaranteed unique. UCUM also defines `foot` and `ft` as designations, which Unitwise will resolve as long as an official designation doesn't resolve first. So for now, I have to advise that you use `foot`.

You should be able to convert to any velocity you can dream of. For instance:

```
Unitwise(1, 'm/s').convert_to("mile/year")
=> #<Unitwise::Measurement value=0.19608944318181818338706380435573637618742E5 unit=mile/year>
```

```
Unitwise(1000, "km/s").convert_to("velocity of light")
=> #<Unitwise::Measurement value=0.00333564095198152 unit=velocity of light>
```

**Comment by sandeepnagra** [comment]
Hi @joshwlewis 

Thanks for your response. I am simply trying to convert speed from m/s to foot/min but unitwise fails to do it. Here's what I error I get:

irb(main):009:0> Unitwise(1, 'm/s').convert_to('foot/min')
Unitwise::ExpressionError: Could not evaluate 'foot/min'.

irb(main):008:0> Unitwise(1, 'm/s').convert_to('ft_i/min')
Unitwise::ExpressionError: Could not evaluate 'ft_i/min'.

Can you point out what am I doing wrong here? I tried both foot & ft_i but neither of that works.

Thanks!

**Comment by sandeepnagra** [comment]
I also tried foot/second & foot/hour, they both worked but foot/minute fails.

irb(main):017:0> Unitwise(1, 'm/s').convert_to("foot/second")
=> #<Unitwise::Measurement value=3.280839895 unit=foot/second>

irb(main):018:0> Unitwise(1, 'm/s').convert_to("foot/minute")
Unitwise::ConversionError: Can't convert 1 m/s to foot/minute.
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/unitwise-2.0.0/lib/unitwise/
measurement.rb:31:in `convert_to'
        from (irb):18
        from c:/Ruby22-x64/bin/irb:11:in `<main>'

irb(main):019:0> Unitwise(1, 'm/s').convert_to("foot/hour")
=> #<Unitwise::Measurement value=0.11811023622047244094488222047244E5 unit=foot/hour>

Any idea why just "foot/minute" is failing?
