### ISSUE TITLE
Unitwise::ConversionError: Can't convert 10 milligram/deciliter to millimole/liter

### ISSUE THREAD

**Issue by rubyDoomsday** [joshwlewis/unitwise#34]
This library is amazing and I have been using it for all our unit conversions however I seem to have run into an issue with a particular measurement.

There seems to be an issue with converting from `mmol/L` to `mg/dL` and I am unclear why. I was able to successfully search for each of the units individually `millimole', `liter`, `milligram` and `deciliter` all return as valid types. However, when I run the below conversion I am met with an error. 

```
Unitwise(10, 'milligram/deciliter').convert_to('millimole/liter')
Unitwise::ConversionError: Can't convert 10 milligram/deciliter to millimole/liter.
```

**Comment by phlegx** [comment]
Hi @rubyDoomsday! The problem is, that `gram` is a **mass** property and `mole` is a **amount of substance** property. Please see this file: [derived_unit.yaml#L106](https://github.com/joshwlewis/unitwise/blob/master/data/derived_unit.yaml#L106)

**Comment by rubyDoomsday** [comment]
Tried to do some debugging myself, and this is what I have found:
```
> Unitwise(10, 'milligram/deciliter').compatible_with?(Unitwise(10, 'milligram/deciliter'))
=> true
```

**Comment by rubyDoomsday** [comment]
Hey @phlegx Thanks for the quick reply. I see what you are saying here, but both of these measurements are considered valid when measuring [blood glucose](http://www.joslin.org/info/conversion_table_for_blood_glucose_monitoring.html) and are commonly translated. Do you have any suggestions on how I can proceed?
