### ISSUE TITLE
Degree Réaumur and function_code degree: undefined method

### ISSUE THREAD

**Issue by phlegx** [joshwlewis/unitwise#41]
Hi!

In version 2.1.0 you have added **Degree Réaumur** like:

```yaml
- :names: degree Réaumur
  :symbol: "°Ré"
  :primary_code: "[degRe]"
  :secondary_code: "[degRe]"
  :scale:
    :function_code: degre
    :value: 5.0
    :unit_code: K/4
  :classification: heat
  :property: temperature
  :metric: false
  :special: true
:arbitrary: false
```

but I cannot find this function in [`unitwise/lib/unitwise/functional.rb`.](https://github.com/joshwlewis/unitwise/blob/master/lib/unitwise/functional.rb) Have I overlooked something? Here my issue about **Degree Réaumur** [#21](https://github.com/joshwlewis/unitwise/issues/21)

**Error:**

`undefined method `from_degre' for Unitwise::Functional:Class`

**Comment by phlegx** [comment]
**Here the solution:**

```ruby
module Unitwise
  class Functional < Scale
    def self.to_degre(x)
      4.0 * x / 5.0 - 218.52
    end


    def self.from_degre(x)
      5.0 / 4.0 * (x + 218.52)
    end
  end
end
```

**Comment by joshwlewis** [comment]
Hey @phlegx, I'm glad you were able to figure that out. Any chance you want to open a PR with that change?

**Comment by phlegx** [comment]
Hi @joshwlewis! PR done.
