### ISSUE TITLE
convert_to doesn't work for 'ft' but only for 'foot'

### ISSUE THREAD

**Issue by alexanderhaberstroh** [joshwlewis/unitwise#62]
```
Unitwise(25.0, 'ft').convert_to('mm') # -> ConversionError
Unitwise(25.0, 'foot').convert_to('mm') # -> works
```

Version: 2.2.0

**Comment by joshwlewis** [comment]
`ft` evaluates to `femtotonne` as UCUM favors SI units. You probably want `Unitwise(25.0, '[ft_i]').convert_to('mm')` or `Unitwise(25.0, 'foot').convert_to('mm')`.
